import type { Metadata } from "next";
import styles from "./layout.module.css"
import "./globals.css";
import Menu from "./components/Menu";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import Search from "./components/Search";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	const menuItems: Array<IMenuItems> = [
		{
			title: "最新動態",
			iconText: "B",
			url: "/financialStatements/stocks/2330",
			color: "#CA0813"
		},
		{
			title: "股票健康",
			iconText: "F",
			url: "",
			color: "#198420"
		},
		{
			title: "財務報表",
			iconText: "C",
			url: "",
			color: "#E67820"
		},
		{
			title: "獲利能力",
			iconText: "D",
			url: "",
			color: "#345BA7"
		},
		{
			title: "安全性分析",
			iconText: "E",
			url: "",
			color: "#345BA7"
		},
		{
			title: "成長力分析",
			iconText: "Q",
			url: "",
			color: "#743079"
		},
		{
			title: "價值評估",
			iconText: "J",
			url: "",
			color: "#345BA7"
		},
		{
			title: "董監與籌碼",
			iconText: "G",
			url: "",
			color: "#345BA7"
		},
		{
			title: "關鍵指標",
			iconText: "H",
			url: "",
			color: "#345BA7"
		},
		{
			title: "產品組合",
			iconText: "I",
			url: "",
			color: "#345BA7"
		},
	]

	return (
		<html>
			<body className={styles.wrapper}>
				<AppRouterCacheProvider>
					<div className={styles.header}>
						<Search />
					</div>
					<div className={styles.main}>
						<div className={styles.menu}>
							<Menu items={menuItems} />
						</div>
						<div className={styles.container}>
							{children}
						</div>
					</div>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
